service: redbee-challenge-backend

provider:
  name: aws
  runtime: java8
  environment:
    DYNAMODB_USERS_TABLE: ${self:service}-user-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_USERS_TABLE}"

package:
  artifact: target/scala-2.12/redbee-challenge-backend.jar

functions:
  createUser:
    handler: challenge.backend.handler.CreateUserHandler
    events:
      - http:
          path: user
          method: post
          cors: true
  updateUserInterests:
    handler: challenge.backend.handler.UpdateUserInterestsHandler
    events:
      - http:
          path: user/{userName}
          method: patch
          cors: true
  getUserInterests:
    handler: challenge.backend.handler.GetUserInterestsHandler
    events:
      - http:
          path: user/{userName}
          method: get
          cors: true
  getUsers:
    handler: challenge.backend.handler.GetUsersHandler
    events:
      - http:
          path: user
          method: get
          cors: true
  getDashboard:
    handler: challenge.backend.handler.GetDashboardHandler
    events:
      - http:
          path: user/{userName}/dashboard/{page}
          method: get
          cors: true


resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: userName
            AttributeType: S
        KeySchema:
          -
            AttributeName: userName
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_USERS_TABLE}